config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'bookmarks#index'
  resources :bookmarks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
end

app/models/webmark.rb
class Webmark < ApplicationRecord
  has_many :bookmarks, as: :bookmarkable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def index
    @bookmarks = Bookmark.all
  end

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmarks_params)
    @bookmark.save
    
    redirect_to bookmarks_path
  end

  def show
    @bookmark = Bookmark.find(params[:id])
  end

  def edit
    @bookmark = Bookmark.find(params[:id])
  end

  def update
    @bookmark = Bookmark.find(params[:id])
    @bookmark.update(bookmarks_params)

    redirect_to bookmarks_path
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy

    redirect_to bookmarks_path
  end

  private
    def bookmarks_params
      params.require(:bookmark).permit(:title, :body, :img_url)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/views/bookmarks/_form.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <%= form_for @bookmark do |f| %>
      <div class="form-group">
        <%= f.text_field :title, class: "form-control input-lg", placeholder: "title" %>
      </div>

      <div class="form-group">
        <%= f.text_field :img_url, class: "form-control input-lg", placeholder: "bookmark_url" %>
      </div>

      <div class="form-group">
        <%= f.text_area :body, rows: "15", class: "form-control input-lg", placeholder: "body" %>
      </div>

      <%= f.submit "Create Bookmark!", class: "btn-success btn-block btn-lg" %>
    <% end %>
    <br>
    <%= link_to 'Back', bookmarks_path %>
  </div>
</div>

app/views/bookmarks/edit.html.erb
<%= render 'form' %>

app/views/bookmarks/index.html.erb
<div class="row">
  <div class="col-sm-4">
    <% @bookmarks.each do |bookmark| %>
      <h3><%= bookmark.title %></h3>
      <p><%= bookmark.body %></p>
      <a href="<%= bookmark.img_url %>" target="_blank"><%= bookmark.img_url %></a>
      <br> 
      <br>
      <%= link_to 'Edit', edit_bookmark_path(bookmark), class: 'btn btn-warning' %>
      <%= link_to 'Delete', bookmark_path(bookmark), method: :delete, data: {confirm: "Are you sure?"}, class: 'btn btn-danger' %> 
      <hr>
    <% end %>
  </div>
  <div class="col-sm-8">
    <img class="img-responsive" src="https://proxy.duckduckgo.com/iu/?u=https%3A%2F%2Fbuildinglocal.files.wordpress.com%2F2011%2F10%2Fbarichara4.jpg&f=1" alt="">
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <img class="img-responsive" src="https://images.unsplash.com/photo-1504754524776-8f4f37790ca0?auto=format&fit=crop&w=750&q=80" alt="">
  </div>
</div>

app/views/bookmarks/new.html.erb
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bukmark-App</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Latest compiled and minified CSS -->
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
      <!-- Jquery -->
      <script
      src="https://code.jquery.com/jquery-3.2.1.min.js"
      integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
      crossorigin="anonymous"></script>
      <!-- Latest compiled and minified JavaScript -->
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Bukmark-App</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav"> 
            <li><%= link_to 'Web Development', bookmarks_path %></li>
            <li><%= link_to 'News'%></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'New Bukmark', new_bookmark_path%></li> 
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>